### ISSUE TITLE
Crash when click on "View server info" on server list

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#46] opened 2021-05-11 16:39 UTC
Not always, but sometimes the game crashes. I'll attach the crash logs.

[crash-2021-05-11-12-48-43.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6460673/crash-2021-05-11-12-48-43.zip)

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)
> 
> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.1,48,4554

**Comment by tmp64** [comment] 2021-05-12 05:10
It looks like a problem with RevEmu.

1. What client do you use?
2. Were you connected to a server at the moment of crash?
3. Does it only happen when viewing specific servers?
4. Does it happen without BHL installed?

**Comment by gundogfan** [comment] 2021-05-12 22:42
1. [revemu.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6468944/revemu.zip)
2. I wasn't.
3. Testing right now, it happened twice with the same server but I'm pretty sure it happened with other servers as well.
4. Can't provide this info since I don't have the default client :/

I'm sorry I can't help with this one.

**Comment by gundogfan** [comment] 2021-05-14 01:54
Update: it kept on happening with the same server, which is not located near my country so the ping is actually really high, that could be the reason. I'll close this one.

**Comment by tmp64** [comment] 2021-05-14 11:10
There may be a conflict between the client and RevEmu since the client links with SteamAPI library but expects a newer version of it. There have been reports of random crashes in Rev libraries that I couldn't reproduce and that only occur with BHL.

Here's an original client.dll from game version 4554. Please, test when you have a moment.
[client_dll_4554.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6478362/client_dll_4554.zip)

**Comment by gundogfan** [comment] 2021-05-14 20:35
Tested with original client.dll. Didn't crash. I tried 30 times (right click, view server info) and it didn't crash. Whilst with BHL it'd crash in less than 10 times.

**Comment by tmp64** [comment] 2021-05-15 03:02
Here's a version of the client with SteamAPI disabled. Please, test if it crashes.
[client_no_steam_api.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6481810/client_no_steam_api.zip)

**Comment by gundogfan** [comment] 2021-05-15 07:20
It does crash. 
In addition, I just noticed it also crashes when you "view server info" and the server appears as "not responding", but that also happens with default client.dll so no idea.

**Comment by tmp64** [comment] 2021-05-22 04:13
I've finally been able to reproduce the issue reliably.

The game crashes if you close server info dialog before server browser receives server information from SteamAPI. It happens with and without BHL.

When the dialog is closed, it sends a cancel request to SteamAPI but my guess is that Rev doesn't always handle them. Since the dialog is destroyed, once the response is received, it calls an invalid function and that leads to different crashes.

I'm going to close this as the bug is in RevEmu.

**Closed by tmp64** 2021-05-22 04:13 UTC
Labels: bug, client, wontfix

**Comment by gundogfan** [comment] 2021-05-22 22:17
Understood, nothing to be done then. Good job anyway!
