### ISSUE TITLE
Custom crosshair disappears after the start of demo recording 

### ISSUE THREAD

**Issue by SmileyAG** [tmp64/BugfixedHL-Rebased#32] opened 2021-04-12 06:07 UTC
Proof: 

https://user-images.githubusercontent.com/58108407/114349057-71a5bc80-9b78-11eb-8e69-bee793188e8d.mp4

**Comment by SmileyAG** [comment] 2021-04-13 14:28
More proof from my friends:


https://user-images.githubusercontent.com/58108407/114569356-f3cfd700-9c85-11eb-9c06-1b7b25c904f9.mp4

https://youtu.be/2FQgC7OZxQY 

@tmp64

**Comment by tmp64** [comment] 2021-04-14 08:29
The issue is caused by the server resetting the HUD when `fullupdate` is received (which is sent when demo recording is started). This issue was fixed in BugfixedHL server, which I used when trying to reproduce the problem.

**Closed** 2021-04-14 09:24 UTC
Labels: bug, client
