### ISSUE TITLE
BHL Server not working

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#92] opened 2021-10-01 23:02 UTC
I installed BHL on my server (Linux) but it doesn't load, it crashes instead, showing this message on console:

> Game DLL version mismatch
> DLL version is 140, engine version is 140
> The game DLL for valve appears to be outdated, check for updates

This is my server's info:

> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> ReHLDS version: 3.8.0.702-dev
> Build date: 18:22:55 Nov  8 2020 (2402)
> Build from: https://github.com/dreamstalker/rehlds/commit/543728d

> AMX Mod X 1.9.0.5271 (http://www.amxmodx.org)
> Compiled: Jun 24 2020 13:53:30
> Built from: https://github.com/alliedmodders/amxmodx/commit/5eea3e5
> Build ID: 5271:5eea3e5
> Core mode: JIT+ASM32

> Metamod v1.21p39  2016/12/24 (5:13)
> by Will Day
>    http://www.metamod.org/
>  Patch: Metamod-P (mm-p) v37
>  by Jussi Kivilinna
>     http://metamod-p.sourceforge.net/
>  Patch: Metamod-P (mm-p) CMake v39
>  by Sam Vanheer
>     https://github.com/SamVanheer/Metamod-P-CMake
> compiled: Dec 24 2016, 15:54:46 EET (optimized+meta_debug-disabled)

EDIT: I think this is due to ReHLDS which is based on builds 6152/6153. In this case, is it possible to add support?

**Comment by tmp64** [comment] 2021-10-02 01:53
Duplicate of #91

**Closed by tmp64** 2021-10-02 01:53 UTC
Labels: invalid
